### ISSUE TITLE
selecting only intergenic ORFs seems to be strand-specific

### ISSUE THREAD

**Issue by m-jahn** [AlexanderBartholomaeus/smORFer#2]
Hi!
In the smORFer publication it is claimed that the default setting of the workflow is to exclude ORFs that overlap with annotated genes (or, implicitly, are enclosed by annotated genes). Quote:

>ORFs in non-annotated regions where filter by intersectBed and counting read was done using coverageBed

This is also how the script `run_moduleA.sh` seems to be intended, running the options from the `unselect_regions.sh` script.
However, running this script I noticed that the `intersectBed` command is strand-specific (option `-s`). As a result, the ORF output is only filtered for ORFs that overlap annotated genes on the same strand but not the reverse strand. Is this the intended behavior? Because from my personal definition of non-overlapping ORFs I would also exclude overlapping ORFs on the reverse strand. Thanks for clarifying.

**Comment by AlexanderBartholomaeus** [comment]
Hi, 
yes, this is the intended way it should work. There are some reasons why we decided to do it like this:

1. Known small ORFs are often on different strands, we don't want to exclude them
2. NGS protocols are often strand-specific and thus ORFs on different strands can be handled seperately
3. Practically, if you have your regions to exclude and want both strands you can simply duplicate it and make it for both strands

But you are right, the obivious definition of overlapping ORFs includes both strands. I also see that this is not really well described in the [details here in github](https://github.com/AlexanderBartholomaeus/smORFer/tree/master#module-a) and I will add some more words on it.

I hope this helps. Otherwise, please let me know.

Alex

**Comment by m-jahn** [comment]
Thanks for clarification!
